version: '3'
services:
  web:
    image: odoo:8.0
    container_name: odoo8
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    container_name: odoo8_db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
